name: flutter_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.15
  json_annotation: ^4.8.1
  http: ^0.13.4
  device_info_plus: ^9.0.3
  h3_flutter: ^0.6.3
  flutter_svg: ^1.1.0
  flutter_riverpod: ^1.0.4
  flutter_multi_formatter: ^2.5.7
  # flutter_  _cse: ^0.0.1
  adyen_checkout: ^1.0.2
  mobile_scanner: ^5.2.3
  geolocator: ^10.0.0
  lottie: ^1.3.0
  camera: ^0.10.4
  camera_android_camerax: ^0.5.0+22
  path_provider: ^2.0.11
  path: ^1.8.2

  permission_handler: ^10.0.0
  # temporarility removing mapbox due to not having the authorization for it
  # mapbox_maps_flutter: ^2.1.0
  flutter_dotenv: ^5.0.2
  graphql_flutter: ^5.1.0
  drift: ^2.1.0
  sqlite3_flutter_libs: ^0.5.0
  # background_fetch: ^1.3.7
  optional: ^6.1.0+1
  package_info_plus: ^4.1.0
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^6.0.0
  mqtt_client: ^9.7.2
  flutter_modular: ^5.0.3
  share_plus: ^10.0.2
  flutter_driver:
    sdk: flutter
  pin_code_fields: ^7.4.0
  country_picker:
    git:
      url: https://github.com/ridebeam/flutter_country_picker
      ref: master # branch name
  flutter_swiper_plus: 2.0.4
  webview_flutter: ^4.2.2
  nanoid: 1.0.0
  url_launcher: ^6.1.14
  flutter_blue_plus:
    git:
      url: https://github.com/ridebeam/flutter_blue_plus
      ref: 1.8.4-fix-uuid-crash # branch name
  encrypt: ^5.0.1
  collection: ^1.16.0
  fluttertoast: ^8.2.1
  email_validator: ^2.1.17
  intl: ^0.19.0
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  firebase_remote_config: ^4.3.8
  firebase_analytics: ^10.8.0
  mixpanel_flutter: ^2.0.0
  crypto: ^3.0.2
  uni_links: ^0.5.1
  app_settings: 4.1.8
  loader_overlay: ^2.1.0
  flutter_spinkit: ^5.1.0
  flutter_native_splash: ^2.1.0
  google_sign_in: ^5.4.3
  sign_in_with_apple: ^4.3.0
  kakao_flutter_sdk_user: ^1.3.1
  kakao_flutter_sdk_auth: ^1.3.1
  styled_text: ^7.0.0
  sliding_up_panel: ^2.0.0+1
  intercom_flutter: ^8.0.3
  flutter_naver_map: ^1.3.0+1
  vector_math: ^2.1.4
  fluster: ^1.2.0
  in_app_review: ^2.0.6
  firebase_messaging: ^14.4.0
  card_scanner:
    git:
      url: https://github.com/ridebeam/card-scanner-flutter.git
      ref: 5ebf82e9031462a96f440eb9fc55a3fdf4b92d7c
  android_id: ^0.2.0
  super_tooltip: ^2.0.4
  uuid: ^3.0.6
  keyboard_actions: ^4.2.0
  flutter_local_notifications: ^17.2.3
  internet_connection_checker: ^1.0.0+1
  visibility_detector: ^0.4.0+2
  pointycastle: ^3.1.1
  golden_toolkit: ^0.15.0
  clock: ^1.1.1
  adaptive_action_sheet: ^2.0.2
  youtube_player_flutter: ^8.1.2
  cached_network_image: ^3.3.0
  equatable: ^2.0.5
  latlong2: ^0.9.0
  maps_toolkit: ^3.0.0
  pub_semver: ^2.1.4

dependency_overrides:
  flutter_inappwebview: ^6.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  test: ^1.15.4
  flutter_localizations:
    sdk: flutter
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  build_runner: ^2.4.6
  json_serializable: ^6.2.0
  graphql_codegen: ^0.13.5
  drift_dev: ^2.1.0
  modular_test: ^2.0.0
  mockito: ^5.4.0
  flutter_launcher_icons: ^0.11.0
  plugin_platform_interface: ^2.1.4
  url_launcher_platform_interface: ^2.1.2
  pigeon: ^10.1.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
